import {
  ElTag,
  ElTabs,
  ElTabPane,
  ElButton,
  ElScrollbar,
  ElTable,
  ElTableColumn,
  ElForm,
  ElFormItem,
  ElInput,
  ElRow,
  ElCol,
  ElRadioGroup,
  ElRadioButton,
  ElRadio,
  ElOption,
  ElOptionGroup,
  ElSelect,
  ElSelectV2,
  ElDatePicker,
  ElSwitch,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElIcon,
  ElInputNumber,
  ElTooltip,
  ElPopper,
  ElDialog,
  ElPopover,
  ElPopconfirm,
  ElTimePicker,
  ElPagination,
  ElConfigProvider,
  ElSkeleton,
} from 'element-plus'
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(ElTag)
  nuxtApp.vueApp.use(ElConfigProvider)
  nuxtApp.vueApp.use(ElPagination)
  nuxtApp.vueApp.use(ElTabs)
  nuxtApp.vueApp.use(ElTabPane)
  nuxtApp.vueApp.use(ElTimePicker)
  nuxtApp.vueApp.use(ElPopconfirm)
  nuxtApp.vueApp.use(ElPopover)
  nuxtApp.vueApp.use(ElDialog)
  nuxtApp.vueApp.use(ElButton)
  nuxtApp.vueApp.use(ElScrollbar)
  nuxtApp.vueApp.use(ElTable)
  nuxtApp.vueApp.use(ElTableColumn)
  nuxtApp.vueApp.use(ElForm)
  nuxtApp.vueApp.use(ElFormItem)
  nuxtApp.vueApp.use(ElInput)
  nuxtApp.vueApp.use(ElRow)
  nuxtApp.vueApp.use(ElCol)
  nuxtApp.vueApp.use(ElRadioGroup)
  nuxtApp.vueApp.use(ElRadioButton)
  nuxtApp.vueApp.use(ElRadio)
  nuxtApp.vueApp.use(ElOption)
  nuxtApp.vueApp.use(ElOptionGroup)
  nuxtApp.vueApp.use(ElSelect)
  nuxtApp.vueApp.use(ElSelectV2)
  nuxtApp.vueApp.use(ElDatePicker)
  nuxtApp.vueApp.use(ElSwitch)
  nuxtApp.vueApp.use(ElCheckbox)
  nuxtApp.vueApp.use(ElCheckboxButton)
  nuxtApp.vueApp.use(ElCheckboxGroup)
  nuxtApp.vueApp.use(ElIcon)
  nuxtApp.vueApp.use(ElInputNumber)
  nuxtApp.vueApp.use(ElTooltip)
  nuxtApp.vueApp.use(ElPopper)
  nuxtApp.vueApp.use(ElSkeleton)
})
