export const localizedExcelTableLabel = {
  footerLeft: (top: number, bottom: number, total: number) =>
    `Записей от ${top} до ${bottom} из ${total}`,
  first: 'Первая',
  previous: 'Предыдущая',
  next: 'Следующая',
  last: 'Последняя',
  footerRight: {
    selected: 'Выбраны:',
    filtered: 'Отфильтрованы:',
    loaded: 'Загружено:',
  },
  processing: 'Обработка',
  tableSetting: 'Настройки таблицы',
  exportExcel: 'Экспорт Excel',
  importExcel: 'Импорт Excel',
  back: 'Вернуться',
  reset: 'Очистить таблицу',
  sortingAndFiltering: 'Сортировка и Фильтрация',
  sortAscending: 'Сортировка по возрастанию',
  sortDescending: 'Сортировка по убыванию',
  near: '≒ Рядом',
  exactMatch: '= точное совпадение',
  notMatch: '≠ Не совпадает',
  greaterThan: '&gt; Больше, чем',
  greaterThanOrEqualTo: '≥ Больше или Равно',
  lessThan: '&lt; Меньше, чем',
  lessThanOrEqualTo: '≤ Меньше Или Равно',
  regularExpression: '~ Регулярное выражение',
  customFilter: 'Свой фильтр',
  listFirstNValuesOnly: (n: number) =>
    `Перечислите только первые ${n} значения`,
  apply: 'Принять',
  noRecordIsRead: 'Запись не считывается',
  readonlyColumnDetected: 'Обнаружен столбец, доступный только для чтения',
  columnHasValidationError: (name: string, err: string) =>
    `Колонка ${name} имеет ошибку: ${err}`,
  noMatchedColumnName: 'Не найдено совпадающего имени столбца',
  invalidInputValue: 'Недопустимое значение',
  missingKeyColumn: 'Отсутствующий ключ столбеца',
  noRecordIndicator: 'Нет записей',
}
